AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/bundle/**/*
    - tmp/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BlockComments:
  Enabled: false
